# Generated by Django 4.0.6 on 2022-07-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, unique=True, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
