# Generated by Django 4.0.6 on 2022-07-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='event',
        ),
        migrations.AddField(
            model_name='client',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='meetup_bot.event', verbose_name='Мероприятие'),
        ),
    ]
