# Generated by Django 4.0.6 on 2022-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0004_alter_lecture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Должность'),
        ),
    ]
