# Generated by Django 4.0.6 on 2022-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0005_client_first_name_client_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='speaker',
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.ManyToManyField(blank=True, null=True, related_name='lectures', to='meetup_bot.client', verbose_name='Спикеры'),
        ),
    ]
