# Generated by Django 4.0.6 on 2022-07-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0007_alter_lecture_speaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='speaker',
            new_name='speakers',
        ),
    ]
