# Generated by Django 4.0.6 on 2022-07-29 17:11

from django.db import migrations, models
import django.db.models.deletion
import meetup_bot.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0008_rename_speaker_lecture_speakers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['end'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name': 'Донат', 'verbose_name_plural': 'Донаты'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-end'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['end'], 'verbose_name': 'Лекция', 'verbose_name_plural': 'Лекции'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос спикеру', 'verbose_name_plural': 'Вопросы спикеру'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=meetup_bot.models.get_upload_resume_path, verbose_name='Резюме'),
        ),
        migrations.CreateModel(
            name='ProposedLecture',
            fields=[
                ('lecture_title', models.TextField(blank=True, verbose_name='Описание лекции')),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meetup_bot.questionnaire', verbose_name='Анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_lectures', to='meetup_bot.client', verbose_name='Пользователь')),
            ],
        ),
    ]
