# Generated by Django 4.0.6 on 2022-07-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0010_questionnaire_resume_proposedlecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposedlecture',
            options={'verbose_name': 'Предложенная лекция', 'verbose_name_plural': 'Предложенные лекции'},
        ),
    ]
