# Generated by Django 4.0.6 on 2022-08-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0011_alter_proposedlecture_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedlecture',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposedlecture',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_lectures', to='meetup_bot.questionnaire', verbose_name='Анкета'),
        ),
    ]
